### ISSUE TITLE
[Feature] Ability to change the seach engine

### ISSUE THREAD

**Issue by Krafting** [ashwin-pc/hiccup#39]
Hi, I found your software today, and I really enjoy the minimalist look and feel.

I wonder if it's possible, in future release, to have the ability to change the search engine. Google is meh when it comes to privacy etc..

We can change it in the JS file itself, but having the option in the UI and the config file would be cool!

**Comment by ashwin-pc** [comment]
@Krafting, that's a brilliant suggestion. I'd prefer adding it to the config since that let's you have a per config search provider. Definitely adding this to the road map.
